### PR TITLE
Mse week 4 and 5 frontend

### PR DESCRIPTION
**Pull request by HamidurRahman1**
Stories completed related to front end work - 

- https://www.pivotaltracker.com/n/projects/2626708/stories/184366338
- https://www.pivotaltracker.com/n/projects/2626708/stories/184311115
- https://www.pivotaltracker.com/n/projects/2626708/stories/184311110
- https://www.pivotaltracker.com/n/projects/2626708/stories/184311107
- https://www.pivotaltracker.com/n/projects/2626708/stories/184285763

### CODE REVIEW

**Review by s-gorrin — APPROVED** [review]
This all looks good. I know virtually no javascript, but the pages generally look pretty good to me.

I might be seeing things wrong, but it looks like the pane and the background for the login page are the same color. If that's the case (which may not be, since I'm not seeing everything together as it should be), we may want to lighten the background. 

I think we're definitely on track. Thank you for all your work @HamidurRahman1 @amip0020

**Review by nbnkiran — APPROVED** [review]

**Review by sargent-bu — COMMENTED** [review]
I know it's somewhat conventional to return the server status on error, but ultimately is this helpful to the user? I only ask from the perspective of a user not well-versed in server communication.

**Review by sargent-bu — COMMENTED** [review]
I like the logo incorporation! Very good branding inclusion!

**Review by sargent-bu — COMMENTED** [review]
https://www.pivotaltracker.com/story/show/184311125

This seems to be directly related to this story, but we haven't moved it out of Icebox, making the move in Pivotal now.

**Pull request merged**
