### PR TITLE
adding week3 changes: repositories, partial services, models

### PR DESCRIPTION
**Pull request by HamidurRahman1**
This PR covers the work (changes) related to the following pivotal stories - 

- https://www.pivotaltracker.com/n/projects/2626708/stories/184366312
- https://www.pivotaltracker.com/n/projects/2626708/stories/184366311
- https://www.pivotaltracker.com/n/projects/2626708/stories/184366317
- https://www.pivotaltracker.com/n/projects/2626708/stories/184366313

Comments regarding other changes:

- Updated MySQL Driver version to match the AWS MySQL Driver version
- separated properties files to dev and prod
- updated REST endpoints

### CODE REVIEW

**Comment by s-gorrin** [comment]
Looking good. Thank you for the comments in the query code. I am not extremely familiar with password protections in Java. Should the password be hashed before being stored in the Admin class and in the login code? I'm not sure if that's safe since it's just in temporary memory, or if it should be hashed at that point. I assume there will be obfuscation of some kind when passwords are stored in the database, so I'm  not concerned about that part.

Thank you for all the work you're doing.

**Comment by HamidurRahman1** [comment]
We will apply decryption of admins password as they will be stored as encrypted to compare with the given password. This will come in hopefully in the next week changes.

**Comment by sargent-bu** [comment]
@HamidurRahman1 

I will admit, I'm not going to be a very productive reviewer this week because I am completely unfamiliar with the Hibernate and Spring frameworks being utilized here. But, the work in this PR tracks with me. 

- I see positive extension of the customized exceptions, which will add granularity in reporting. 
- I also see utilization of the Spring and Hibernate frameworks to interface with the data handling of the database along with well-thought out function-class definitions to suit our foreseeable DB queries. 
- I was completely unaware of the LinkedIn Security Team library for URL detection in text, that is a neat piece of code utilization and it will greatly simplify URL handling. Kudos there!
- The more comments the better 👍 
- The more commits with well-formed descriptions the better. This may be a personal style preference for me, but the more commits with commit messages, the easier it is to track where everything falls into place and how it was developed. 

Questions for future discussions: 
- What was auto-generated? --> Reason for asking is it is helpful to have auto-generated code marked as such so we can have some basis of understanding what may fail in the auto-generation or how to handle it with testing. 
- Have you thought about a unit test strategy yet? 

Great work as always, Hamid!

**Comment by s-gorrin** [comment]
That's a good point actually. We're seeing huge updates to every file in each commit/PR, and I think committing at each feature, or in otherwise smaller chunks might be easier to do, and much easier to review.

**Comment by HamidurRahman1** [comment]
@sargent-bu @s-gorrin 

- Actually all the interfaces that are marked as @Repository and extend CrudRepository will have code generated at runtime. Best way to test is mocking.
- I have not thought about any specific framework to tests the services and rest APIs. Mockito can be used to do so but more importantly i doubt I will have enough time to do that. We will discuss this in the next team meeting.
- I agree with each commit being specific to a change which is related to commit but I have forgotten or just lazily did in 1 commit. Very bad practice but taking this into consideration from week4.

**Pull request merged**
