### PR TITLE
changing the collection type and fixing the db query

### PR DESCRIPTION
**Pull request by HamidurRahman1**

### CODE REVIEW

**Review by nbnkiran — APPROVED** [review]
Thank you very much Hamid this looks good.

**Review by s-gorrin — APPROVED** [review]
@HamidurRahman1 
I apologize, I read the bug report late. Using `List` to maintain the order makes sense. If there is a good reason to retain the benefits of a `Set`, a [LinkedHashSet](https://docs.oracle.com/javase/6/docs/api/java/util/LinkedHashSet.html) could be useful.

**Comment by HamidurRahman1** [comment]
> @HamidurRahman1 I apologize, I read the bug report late. Using `List` to maintain the order makes sense. If there is a good reason to retain the benefits of a `Set`, a [LinkedHashSet](https://docs.oracle.com/javase/6/docs/api/java/util/LinkedHashSet.html) could be useful.

No worries @s-gorrin. LinkedHashSet indeed preserve the insertion order but generally people stick with super type instead of a concrete type. Also, by our logic, by the time we are retrieving pages from the DB they are already unique cause when we insert them we make sure we are not adding an existing one so at the end in our case Set or List does not matter but Set will randomly store pages according to hashing. We do not want that. Finally, LinkedHashSet would do the job as well but when just populating in average time complexity of LinkedHashSet and ArrayList is same when adding elements to collection but LinkedHashSet goes through many extra overhead of keeping insertion order as is, while List just does it out of the box. Also, we are not doing any computing on the retrieved collection hence I thought about going with List.

**Comment by s-gorrin** [comment]
@HamidurRahman1 
These are all good reasons. I agree that using the simplest types keeps the code faster and more flexible. Thank you for explaining your choice.

**Pull request merged**
